name: External App Sample C Build
on:
  pull_request:
    paths:
      - 'external_app/sample_c/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go to external app directory
        run: cd external_app/sample_c
      - name: Install toolchain
        uses: numworks/setup-arm-toolchain@latest
      - name: Run make build
        run: make build
      - name: Run make check
        run: make check
