name: External App Sample CPP Build
on:
  pull_request:
    paths:
      - 'external_app/sample_cpp/**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Go to external app directory
        run: cd external_app/sample_cpp
      - name: Install C++ toolchain
        uses: numworks/setup-arm-toolchain@latest
      - name: Run make
        run: make
